=== oliverlowbob/5_sem_tests_mandatory2/PhoneCompany/Delivery.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT DeliveryInfo (DeliveryId,Customer,Adress,Delivery,OrderInfo)>
<!ATTLIST DeliveryInfo
  xmlns CDATA #FIXED ''>

<!ELEMENT DeliveryId (#PCDATA)>
<!ATTLIST DeliveryId
  xmlns CDATA #FIXED ''>

<!ELEMENT Delivery (Type,Price,Company)>
<!ATTLIST Delivery
  xmlns CDATA #FIXED ''>

<!ELEMENT OrderInfo (Customer,Adress,Items)>
<!ATTLIST OrderInfo
  xmlns CDATA #FIXED ''>

<!ELEMENT Type (#PCDATA)>
<!ATTLIST Type
  xmlns CDATA #FIXED ''>

<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price
  xmlns CDATA #FIXED ''>

<!ELEMENT Company (Name)>
<!ATTLIST Company
  xmlns CDATA #FIXED ''>

<!ELEMENT Items (Item)+>
<!ATTLIST Items
  xmlns CDATA #FIXED ''>

<!ELEMENT Item (Model,Quantity)>
<!ATTLIST Item
  xmlns CDATA #FIXED ''>

<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model
  xmlns CDATA #FIXED ''>

<!ELEMENT Quantity (#PCDATA)>
<!ATTLIST Quantity
  xmlns CDATA #FIXED ''>

<!ELEMENT Customer (Name,Email,Phone)>
<!ATTLIST Customer
  xmlns CDATA #FIXED ''>

<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email
  xmlns CDATA #FIXED ''>

<!ELEMENT Phone (#PCDATA)>
<!ATTLIST Phone
  xmlns CDATA #FIXED ''>

<!ELEMENT Adress (#PCDATA)>
<!ATTLIST Adress
  xmlns CDATA #FIXED ''>

<!ELEMENT Name (#PCDATA)>
<!ATTLIST Name
  xmlns CDATA #FIXED ''>

=== oliverlowbob/5_sem_tests_mandatory2/PhoneCompany/Delivery.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE DeliveryInfo SYSTEM "Delivery.dtd">
<!-- Delivery.xml stores information about order deliveries -->
<DeliveryInfo>
	<DeliveryId>50</DeliveryId>
	<Customer>
		<Name>Anders Madsen</Name>
		<Email>andersmadsen@gmail.com</Email>
		<Phone>+4520392938</Phone>	
	</Customer>
	<Adress>Stærevej 50, 2200 København N</Adress>
	<Delivery>
		<Type>Express</Type>
		<Price>50</Price>
		<Company>
			<Name>GLS</Name>
		</Company>
	</Delivery>
	<OrderInfo>
		<Customer>
			<Name>Anders Madsen</Name>
			<Email>andersmadsen@gmail.com</Email>
			<Phone>+4520392938</Phone>
		</Customer>
		<Adress>Stærevej 50, 2200 København N</Adress>
		<Items>
			<Item>
				<Model>iPhone 8</Model>
				<Quantity>1</Quantity>
			</Item>
			<Item>
				<Model>Samsung Galaxy S10</Model>
				<Quantity>1</Quantity>
			</Item>
		</Items>
	</OrderInfo>	
</DeliveryInfo>
