=== oliverlowbob/5_sem_tests_mandatory2/PhoneCompany/Order.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT OrderInfo (OrderId,Items)>
<!ATTLIST OrderInfo
  xmlns CDATA #FIXED ''>

<!ELEMENT OrderId (#PCDATA)>
<!ATTLIST OrderId
  xmlns CDATA #FIXED ''>

<!ELEMENT Items (Item)+>
<!ATTLIST Items
  xmlns CDATA #FIXED ''>

<!ELEMENT Item (Model,Quantity)>
<!ATTLIST Item
  xmlns CDATA #FIXED ''>

<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model
  xmlns CDATA #FIXED ''>

<!ELEMENT Quantity (#PCDATA)>
<!ATTLIST Quantity
  xmlns CDATA #FIXED ''>

=== oliverlowbob/5_sem_tests_mandatory2/PhoneCompany/Order.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE OrderInfo SYSTEM "Order.dtd">
<!-- Order.xml stores information about orders from customers -->
<OrderInfo>
	<OrderId>256</OrderId>
	<Items>
		<Item>
			<Model>iPhone 8</Model>
			<Quantity>1000</Quantity>
		</Item>
		<Item>
			<Model>Samsung Galaxy S10</Model>
			<Quantity>1000</Quantity>
		</Item>
	</Items>
</OrderInfo>
