=== oliverlowbob/5_sem_tests_mandatory2/PhoneCompany/Storage.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT StorageInfo (Items)>
<!ATTLIST StorageInfo
  xmlns CDATA #FIXED ''>

<!ELEMENT Items (Item)+>
<!ATTLIST Items
  xmlns CDATA #FIXED ''>

<!ELEMENT Item (Id,Category,Model,Price,Quantity)>
<!ATTLIST Item
  xmlns CDATA #FIXED ''>

<!ELEMENT Id (#PCDATA)>
<!ATTLIST Id
  xmlns CDATA #FIXED ''>

<!ELEMENT Category (#PCDATA)>
<!ATTLIST Category
  xmlns CDATA #FIXED ''>

<!ELEMENT Model (#PCDATA)>
<!ATTLIST Model
  xmlns CDATA #FIXED ''>

<!ELEMENT Price (#PCDATA)>
<!ATTLIST Price
  xmlns CDATA #FIXED ''>

<!ELEMENT Quantity (#PCDATA)>
<!ATTLIST Quantity
  xmlns CDATA #FIXED ''>

=== oliverlowbob/5_sem_tests_mandatory2/PhoneCompany/Storage.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE StorageInfo SYSTEM "Storage.dtd">
<!-- Storage.xml stores information about the storage on items on the depot -->
<StorageInfo>
	<Items>
		<Item>
			<Id>256773113</Id>
			<Category>Phone</Category>
			<Model>Samsung Spacestar 500</Model>
			<Price>8700</Price>
			<Quantity>26</Quantity>
		</Item>
		<Item>
			<Id>2786868372</Id>
			<Category>Phone</Category>
			<Model>iPhone MoneyStealer</Model>
			<Price>15000</Price>
			<Quantity>250</Quantity>
		</Item>		
	</Items>
</StorageInfo>
